# Generated by Django 5.2.5 on 2025-08-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('HOSPITAL_ADMIN', 'Hospital Admin'), ('ADMIN', 'Platform Admin'), ('BLOOD_DONOR', 'Blood Donor')], default='PATIENT', max_length=255),
        ),
    ]
